version: "2.4"
services:
  backend:
    image: 400936075989.dkr.ecr.us-east-1.amazonaws.com/crawl-app-backend
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: crawldev
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local
