version: "3.7"
services:
  backend:
    build:
      context: ./backend
    image: crawl-app-backend
    stdin_open: false
    tty: true
    command: ./local.sh
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    links:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: crawldev
