version: "3.8"
services:
  backend:
    build:
      context: ./backend
    image: crawl-app-backend
    command: bash -c "pip install -r requirements.txt && ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    links:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: crawldev
