version: "3.7"
services:
  traefik:
    image: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.Address=:80"
      - "--entrypoints.https.Address=:443"
      - "--certificatesresolvers.myresolver.acme.email=support@epicdesignlabs.com"
      - "--certificatesresolvers.myresolver.acme.storage=/data/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=http"
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - certificate-data:/data
    labels:
      - "traefik.enable=true"
      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # global redirect to https
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=http"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"
  backend:
    image: 400936075989.dkr.ecr.us-east-1.amazonaws.com/crawl-app-backend
    restart: always
    links:
      - db
      - crawler
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=(Host(`linkapp.epicsandbox.com`) && (PathPrefix(`/api/`)||PathPrefix(`/auth/`)||PathPrefix(`/admin/`)||PathPrefix(`/static/`)))"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
    environment:
      ENV: staging
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "3"
  frontend:
    image: 400936075989.dkr.ecr.us-east-1.amazonaws.com/crawl-app-frontend
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=(Host(`linkapp.epicsandbox.com`) && PathPrefix(`/`))"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
  crawler:
    image: 400936075989.dkr.ecr.us-east-1.amazonaws.com/crawl-app-crawler
    restart: always
    links:
      - db
    environment:
      ENV: staging
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "3"
  scheduler:
    image: 400936075989.dkr.ecr.us-east-1.amazonaws.com/crawl-app-scheduler
    restart: always
    links:
      - db
    environment:
      ENV: staging
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local
  certificate-data:
    driver: local
