version: "3.7"
services:
  backend:
    image: 400936075989.dkr.ecr.us-east-1.amazonaws.com/crawl-app-backend
    restart: always
    ports:
      - "8001:8000"
    links:
      - crawler
    environment:
      ENV: production
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "3"
  frontend:
    image: 400936075989.dkr.ecr.us-east-1.amazonaws.com/crawl-app-frontend
    restart: always
    ports:
      - "8000:3000"
  crawler:
    image: 400936075989.dkr.ecr.us-east-1.amazonaws.com/crawl-app-crawler
    restart: always
    environment:
      ENV: production
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "3"
  scheduler:
    image: 400936075989.dkr.ecr.us-east-1.amazonaws.com/crawl-app-backend
    command: sleep 3600
    restart: always
