version: "2.4"
services:
  backend:
    image: 400936075989.dkr.ecr.us-east-1.amazonaws.com/crawl-app-backend
    restart: always
    ports:
      - "8001:8000"
    links:
      - verifier
    environment:
      ENV: production
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "3"
    mem_limit: 256M
  frontend:
    image: 400936075989.dkr.ecr.us-east-1.amazonaws.com/crawl-app-frontend
    restart: always
    ports:
      - "8000:3000"
    mem_limit: 128M
  verifier:
    image: 400936075989.dkr.ecr.us-east-1.amazonaws.com/crawl-app-verifier
    restart: always
    environment:
      ENV: production
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "3"
    mem_limit: 256M
  scheduler:
    image: 400936075989.dkr.ecr.us-east-1.amazonaws.com/crawl-app-scheduler
    restart: always
    environment:
      ENV: production
    mem_limit: 64M
  uptimer:
    image: 400936075989.dkr.ecr.us-east-1.amazonaws.com/crawl-app-uptimer
    restart: always
    environment:
      ENV: production
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "3"
    mem_limit: 64M
